from django.urls import path
from ..views.Temp_unit import TempUnitList, TempUnitListPending, TempUnitPublish, TempUnitUpdate, TempUnitCreate, TempUnitRetrieve, TempUnitDelete

urlpatterns = [
    path(
        'admin/company/<int:company_id>/courses/<int:course_id>/unit/<int:unit_id>/temp_unit',
        TempUnitList.as_view(),
        name='temp-unit-admin-list'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/unit/<int:unit_id>/temp_unit',
        TempUnitList.as_view(),
        name='temp-unit-trainer-list'
    ),
    path(
        'admin/company/<int:company_id>/courses/<int:course_id>/unit/<int:unit_id>/temp_unit/pending',
        TempUnitListPending.as_view(),
        name='temp-unit-admin-list-pending'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/unit/<int:unit_id>/temp_unit/pending',
        TempUnitListPending.as_view(),
        name='temp-unit-trainer-list-pending'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/temp_unit', 
        TempUnitCreate.as_view(), 
        name='temp_unit-trainer-create'
    ),
    path(
        'admin/company/<int:company_id>/courses/<int:course_id>/temp_unit/<int:temp_unit_id>', 
        TempUnitRetrieve.as_view(), 
        name='temp_unit-admin-retrive'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/temp_unit/<int:temp_unit_id>', 
        TempUnitRetrieve.as_view(), 
        name='temp_unit-trainer-retrive'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/temp_unit/<int:temp_unit_id>/publish', 
        TempUnitPublish.as_view(), 
        name='temp_unit-trainer-publish'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/temp_unit/<int:temp_unit_id>', 
        TempUnitUpdate.as_view(), 
        name='temp_unit-trainer-update'
    ),
    path(
        'trainer/company/<int:company_id>/courses/<int:course_id>/temp_unit/<int:temp_unit_id>', 
        TempUnitDelete.as_view(), 
        name='temp_unit-trainer-delete'
    ),
]