# Generated by Django 5.0.6 on 2024-06-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_joining_date'),
        ('system', '0002_alter_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=75)),
                ('company_email', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('DZ', 'Algeria'), ('BH', 'Bahrain'), ('EG', 'Egypt'), ('IQ', 'Iraq'), ('JO', 'Jordan'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('LY', 'Libya'), ('MR', 'Mauritania'), ('MA', 'Morocco'), ('OM', 'Oman'), ('PS', 'Palestine'), ('QA', 'Qatar'), ('SA', 'Saudi Arabia'), ('SD', 'Sudan'), ('SY', 'Syria'), ('TN', 'Tunisia'), ('AE', 'United Arab Emirates'), ('YE', 'Yemen')], default='SY', max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=10)),
                ('company_size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='S', max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('created_day', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_name', models.CharField(max_length=255)),
                ('subscription_term', models.DurationField()),
                ('courses_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.admin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.company')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Notfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.admin_contract')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.owner'),
        ),
        migrations.CreateModel(
            name='Owner_Notfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.company')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.planes')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee_Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.company')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee_Notfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.trainee_contract')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.company')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Notfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.trainer_contract')),
            ],
        ),
    ]
