# Generated by Django 5.0.6 on 2024-06-30 21:28

import django.db.models.deletion
import system.models.Course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_rename_contract_admin_notfication_admin_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Trainer_Course',
            new_name='Trainer_Contract_Course',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='editpdf',
            name='additional_resources',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='additional_resources',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_multi_choice',
        ),
        migrations.RemoveField(
            model_name='test',
            name='required_mark',
        ),
        migrations.RemoveField(
            model_name='trainer_contract_course',
            name='trainer',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='admin_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.admin_contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.Course.Course.course_image_path),
        ),
        migrations.AddField(
            model_name='course',
            name='pref_description',
            field=models.TextField(default='pref_description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(through='system.Trainer_Contract_Course', to='system.trainer_contract'),
        ),
        migrations.AddField(
            model_name='question',
            name='xp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='full_mark',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='full_xp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer_contract_course',
            name='trainer_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.trainer_contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editpdf',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='editpdf',
            name='state',
            field=models.CharField(choices=[('PR', 'InProgress'), ('PE', 'Pending'), ('PU', 'Published')], max_length=2),
        ),
        migrations.AlterField(
            model_name='editunit',
            name='state',
            field=models.CharField(choices=[('PR', 'InProgress'), ('PE', 'Pending'), ('PU', 'Published')], max_length=2),
        ),
        migrations.AlterField(
            model_name='editvideo',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='editvideo',
            name='state',
            field=models.CharField(choices=[('PR', 'InProgress'), ('PE', 'Pending'), ('PU', 'Published')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='additional_resources',
            field=models.ManyToManyField(to='system.additional_resources'),
        ),
    ]
