# Generated by Django 5.0.6 on 2024-07-01 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_alter_enrollment_completed_at"),
        ("system", "0006_additional_resources_and_more"),
    ]

    operations = []
