# Generated by Django 5.0.6 on 2024-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_merge_20240701_1601"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="trainer_contract",
            new_name="trainee_contract",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="trainer_contract",
            new_name="trainee_contract",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="xp_avg",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="reply",
            name="dislikes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="likes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
