# Generated by Django 5.0.6 on 2024-07-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_rename_trainer_contract_enrollment_trainee_contract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='owner',
        ),
    ]
