# Generated by Django 5.0.6 on 2024-07-05 14:22

import system.models.Company
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rename_user_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.Company.Company.logo_image_path),
        ),
    ]
