# Generated by Django 5.0.6 on 2024-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(choices=[('DZ', 'Algeria'), ('BH', 'Bahrain'), ('EG', 'Egypt'), ('IQ', 'Iraq'), ('JO', 'Jordan'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('LY', 'Libya'), ('MR', 'Mauritania'), ('MA', 'Morocco'), ('OM', 'Oman'), ('PS', 'Palestine'), ('QA', 'Qatar'), ('SA', 'Saudi Arabia'), ('SD', 'Sudan'), ('SY', 'Syria'), ('TN', 'Tunisia'), ('AE', 'United Arab Emirates'), ('YE', 'Yemen')], default='SY', max_length=2)),
                ('is_trainee', models.BooleanField(default=False)),
                ('is_trainer', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
