# Generated by Django 5.0.6 on 2024-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
